import test from 'node:test';
import assert from 'node:assert/strict';
import { Window } from 'happy-dom';
import 'fake-indexeddb/auto';
import { IDBObjectStore } from 'fake-indexeddb';

test('interface editing flows use the real app modules and local database', async () => {
  const nativeSetTimeout=globalThis.setTimeout;
  globalThis.setTimeout=(fn,ms,...args)=>{const timer=nativeSetTimeout(fn,ms,...args);if(ms>=5000)timer.unref();return timer;};
  const window=new Window({url:'http://localhost/chumlog/'});
  window.addEventListener('error',e=>console.error('DOM error:',e.error));
  window.document.body.innerHTML='<div id="app"></div>';
  for(const key of ['window','document','location','navigator','Node','FormData','HTMLDialogElement']) Object.defineProperty(globalThis,key,{value:key==='window'?window:window[key],configurable:true});
  // Emulate native modal methods not implemented by the DOM test environment.
  window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
  window.HTMLDialogElement.prototype.close=function(){this.open=false;};
  window.scrollTo=()=>{};
  delete window.BroadcastChannel;
  await import('../app/app.js');
  const db=await import('../app/db.js');
  const doc=window.document;
  const wait=async check=>{for(let i=0;i<100;i++){if(await check()) return; await new Promise(r=>setTimeout(r,5));}throw Error('Timed out waiting for UI');};
  const click=(label,scope=doc)=>{
    const button=[...scope.querySelectorAll('button')].find(b=>(b.getAttribute('aria-label')||b.textContent).trim()===label);
    assert.ok(button,`Button: ${label}`); button.click();
  };
  const fill=(name,value)=>{const input=doc.querySelector(`[name="${name}"]`); assert.ok(input,`Missing ${name}: ${doc.body.innerHTML}`);input.value=value;input.dispatchEvent(new window.Event('input',{bubbles:true}));};
  const editor=()=>doc.querySelector('dialog.editor');
  const submit=async()=>{editor().querySelector('form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>!editor().open);};
  const navigate=async hash=>{window.location.hash=hash;window.dispatchEvent(new window.HashChangeEvent('hashchange'));await new Promise(r=>setTimeout(r,10));};
  click('Add person');fill('name','UI Test Person');fill('emoji','🐦');await submit();
  let person=(await db.snapshot()).data.people[0];
  assert.equal(person.emoji,'🐦');
  await navigate(`#person/${person.id}`);
  assert.match(doc.querySelector('h1').textContent,/UI Test Person/);
  click('Edit',doc.querySelector('.profile-header'));fill('name','Renamed Person');fill('emoji','🪴');await submit();
  assert.equal(doc.querySelector('.profile-header .avatar').textContent,'🪴');
  assert.equal((await db.snapshot()).data.people[0].name,'Renamed Person');
  click('Add note');fill('text','<img src=x onerror=alert(1)>\nSecond line');await submit();
  assert.equal(doc.querySelectorAll('.entry img').length,0);
  click('Edit',doc.querySelector('.notes-section'));fill('text','Edited note');await submit();
  assert.equal((await db.snapshot()).data.notes[0].text,'Edited note');
  click('Delete',doc.querySelector('.notes-section'));click('Delete',doc.querySelector('dialog.confirmation'));
  await wait(async()=>(await db.snapshot()).data.notes.length===0);
  click('Add reminder');fill('text','Dated item');fill('date','2026-10-01');await submit();
  assert.equal((await db.snapshot()).data.reminders[0].date,'2026-10-01');
  click('Done',doc.querySelector('.reminders-section'));await wait(async()=>(await db.snapshot()).data.reminders[0].completed);
  await wait(()=>doc.querySelector('.completed-items'));
  click('Reopen',doc.querySelector('.completed-items'));await wait(async()=>!(await db.snapshot()).data.reminders[0].completed);
  click('Add important date');fill('label','Birthday');fill('month','09');fill('day','19');await submit();
  click('Add important date');fill('label','One-off date');
  const repeat=doc.querySelector('[name="yearly"]');repeat.checked=false;repeat.dispatchEvent(new window.Event('change'));fill('date','2099-10-01');await submit();
  assert.equal((await db.snapshot()).data.importantDates.length,2);
  const oneOff=()=>[...doc.querySelectorAll('.dates-section .entry')].find(x=>x.textContent.includes('One-off date'));
  click('Edit',oneOff());fill('label','Renamed date');fill('date','2099-10-02');await submit();
  assert.equal((await db.snapshot()).data.importantDates.find(x=>x.label==='Renamed date').date,'2099-10-02');
  click('Delete',[...doc.querySelectorAll('.dates-section .entry')].find(x=>x.textContent.includes('Renamed date')));click('Delete',doc.querySelector('dialog.confirmation'));
  await wait(async()=>(await db.snapshot()).data.importantDates.length===1);
  click('Add reminder');fill('text','Undated reminder');await submit();
  assert.equal((await db.snapshot()).data.reminders.find(x=>x.text==='Undated reminder').date,null);
  click('Log contact');fill('date','2026-01-01');fill('type','call');await submit();
  assert.match(doc.querySelector('.profile-meta').textContent,/Last talked/);
  assert.equal(doc.querySelector('.contacts-section .entry-text'),null);
  assert.doesNotMatch(doc.querySelector('.contacts-section').textContent,/null/);
  assert.doesNotMatch(doc.querySelector('.notes-section').textContent,/null/);
  click('Edit',doc.querySelector('.contacts-section'));fill('date','2025-12-31');await submit();
  assert.equal((await db.snapshot()).data.contacts[0].date,'2025-12-31');
  click('Add reminder');fill('text','Dated reminder');fill('date','2026-10-02');fill('time','14:00');await submit();
  await navigate('#coming-up');
  assert.equal(doc.querySelectorAll('.agenda-item').length,3);
  assert.match(doc.querySelector('main').textContent,/Dated reminder/);
  await navigate('#people');
  assert.match(doc.querySelector('.person-row').textContent,/Last contact/);
  assert.equal(doc.querySelector('.person-row .avatar').textContent,'🪴');
  const search=doc.querySelector('#search');search.value='No match';search.dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.equal(doc.querySelectorAll('.person-row').length,0);
  search.value='RENAMED';search.dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.equal(doc.querySelectorAll('.person-row').length,1);
  click('Random person');await wait(()=>window.location.hash===`#person/${person.id}`);
  await navigate(`#person/${person.id}`);
  // A failed write must leave the text in the editor and the saved data intact.
  click('Add note');fill('text','Unsaved draft');
  const realPut=IDBObjectStore.prototype.put;
  IDBObjectStore.prototype.put=function(){throw new DOMException('Storage failure','QuotaExceededError');};
  editor().querySelector('form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
  await wait(()=>!editor().querySelector('.error').hidden);
  IDBObjectStore.prototype.put=realPut;
  assert.equal(editor().open,true);assert.equal(doc.querySelector('[name="text"]').value,'Unsaved draft');
  await submit();
  // Export through the Settings action, then import the exact downloaded JSON.
  let downloadUrl;
  window.HTMLAnchorElement.prototype.click=function(){if(this.download)downloadUrl=this.href;};
  await navigate('#settings');click('Export data');await wait(()=>downloadUrl);
  const backup=await (await fetch(downloadUrl)).json();
  const beforeImport=(await db.snapshot()).data;
  const input=doc.querySelector('#import-file');
  const upload=async text=>{Object.defineProperty(input,'files',{value:[{size:text.length,text:async()=>text}],configurable:true});input.dispatchEvent(new window.Event('change'));await new Promise(r=>setTimeout(r,20));};
  await upload('{invalid');assert.match(doc.querySelector('.toast').textContent,/Invalid/);
  assert.deepEqual((await db.snapshot()).data,beforeImport);
  await upload(JSON.stringify(backup));assert.equal(doc.querySelector('dialog.confirmation').open,true);
  click('Cancel',doc.querySelector('dialog.confirmation'));assert.deepEqual((await db.snapshot()).data,beforeImport);
  await upload(JSON.stringify(backup));click('Replace data',doc.querySelector('dialog.confirmation'));
  await wait(()=>!doc.querySelector('dialog.confirmation').open);
  assert.deepEqual((await db.snapshot()).data,beforeImport);
  await navigate(`#person/${person.id}`);
  click('Edit',doc.querySelector('.profile-header'));click('Delete person');
  click('Delete',doc.querySelector('dialog.confirmation'));
  await wait(async()=>(await db.snapshot()).data.people.length===0);
  const after=(await db.snapshot()).data;
  for(const rows of Object.values(after)) assert.equal(rows.length,0);
  await window.happyDOM.abort();
  globalThis.setTimeout=nativeSetTimeout;
});
